default_context:
  project_name: "ProjectGenerator"
  _pkg_name: "{{ cookiecutter.project_name|lower|replace(' ', '') }}"
  _read_from_file: true
  spring_version: "2.7.8"
  java_version: 19
  db: mysql
  _dependency:
    - h2
    - lombok
    - spring-web
    - jpa
    - persistence


resource_name:
  - User
  - Customer
  - Order